language: cpp
env:
- BOARD=uno
- BOARD=yun
compiler:
 - gcc

before_install:
 - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
 - sudo apt-get update -qq
install:
 # g++4.8
 - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi
 #arduino
 - wget http://downloads-02.arduino.cc/arduino-1.5.8-linux64.tgz
 - tar -xvf arduino-1.5.8-linux64.tgz
 - sudo mv arduino-1.5.8/ /usr/local/share/arduino
 #leo
 - npm install -g leo
 - leo config set ide.path /usr/local/share/arduino
 - chmod u+x initexamples.sh

script:
 - ./initexamples.sh $BOARD